### ISSUE TITLE
Compatibilidade com abntex2

### ISSUE THREAD

**Issue by evandrocoan** [royertiago/ufsctex-template#1]
Estou tentando compilar com abntex2, mas tenho o seguinte erro:

```latex
latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode" -use-make template.tex
Latexmk: This is Latexmk, John Collins, 19 Jan. 2017, version: 4.52c.
Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex -interaction=nonstopmode  -recorder  "template.tex"'
------------
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6300)
entering extended mode
(template.tex
LaTeX2e <2017-04-15>
Babel <3.9r> and hyphenation patterns for 76 language(s) loaded.

! LaTeX Error: File `ufsctex/ufsctex.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name:
! Emergency stop.
<read *>

l.4

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on template.log.
=== TeX engine is 'pdfTeX'
===========Latexmk: Missing input file: 'ufsctex/ufsctex.cls' from line
  '! LaTeX Error: File `ufsctex/ufsctex.cls' not found.'
Latexmk: Missing input file: 'ufsctex/ufsctex.cls' from line
  '! LaTeX Error: File `ufsctex/ufsctex.cls' not found.'
Latexmk: 'pdflatex': source file 'ufsctex/ufsctex.cls' doesn't exist. I'll try making it...
------------
Running 'make "ufsctex/ufsctex.cls"'
------------
make: *** No rule to make target 'ufsctex/ufsctex.cls'.  Stop.
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'template.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.

```

Então comecei a pesquisar e procurar novos templete e encontrei a seguinte mensagem:

> Pré-requisitos
> --------------
> Como a norma da BU/UFSC é baseada nas normas ABNT, o ufscThesis usa o 
template ABNTeX como base, modificando-o onde a norma da BU/UFSC difere
da ABNT.

> Isso significa que é necessário ter o ABNTeX instalado na sua distribuição
LaTeX. Informações e download do ABNTeX estão disponíveis no sítio
eletrônico do projeto: http://www.abntex.net.br/

> **A versão de ABNTeX sobre a qual o ufscThesis foi construida foi a 0.8.2,**
considerada a última estável. As versões mais atuais do ABNTeX não
funcionam corretamente com o ufscThesis, motivo pelo qual a versão 0.8.2
(assim como instruções para instalação) pode ser encontrada anexa (no
diretório "abntex").

> O ufscThesis foi testado nas distribuições de LaTeX texlive (linux) e
MiKTeX (windows).

Há um outra proposta de trabalho em https://github.com/mateusduboli/ufsc-thesis-latex, mas não parece completa como esta obra.

Há como atualizar estre trabalho para uso do abntex2?

Caso seja de interesse, há também um modelo de trabalho abntex2 em:

1. [abntex2-modelo-trabalho-academico.tex](https://github.com/abntex/abntex2/blob/master/doc/latex/abntex2/examples/abntex2-modelo-trabalho-academico.tex)

**Comment by royertiago** [comment]
Note que este repositório usa submódulos, então ele deve ser clonado com

    git clone --recursive https://github.com/royertiago/ufsctex-template

(ou então você pode executar `git submodule update --init` após clonar o repositório do jeito "tradicional").
Feito isso, se você tiver o `abntex` instalado, o modelo deve compilar corretamente.

Como não conheço muito sobre LaTeX, atualizar esta classe para usar o abnTeX2 não parece ser uma tarefa trivial (o abnTeX2 aparentemente não é um _drop-in replacement_ para o abnTeX, e o ufscThesis original redefine vários comandos internos do abnTeX); talvez seja mais fácil começar do zero com o abnTeX2.

Esta classe é software livre, sinta-se à vontade para fazer esta atualização você mesmo.

**Comment by evandrocoan** [comment]
Obrigado pelo tempo 👍 

> Note que este repositório usa submódulos

Ops, foi exatamente esse o erro que está sendo mostra no log.

> ufscThesis original redefine vários comandos internos do abnTeX

Isso é um problema. Vou perguntar e pesquisar sobre a existência de um template já atualizado. Provavelmente não deve existir algum, assim acredito ser mais fácil pegar um template padrão para o abntex2 como o do link a cima e este seu, e utilizar eles como exemplo para ir escrevendo o código de um novo template.

## Update

Depois de analisar um dos forks the `mateusduboli` encontrei um outro template:

1. https://github.com/AdrianoRuseler/abntex2-ufsc

Esse parece ser bem completo.

___

Atualizei a mensagem de erro, depois de clonar corretamente o repositório:
```
$ git clone --recursive https://github.com/royertiago/ufsctex-template
Cloning into 'ufsctex-template'...
remote: Counting objects: 133, done.
remote: Total 133 (delta 0), reused 0 (delta 0), pack-reused 133
Receiving objects: 100% (133/133), 48.18 KiB | 0 bytes/s, done.
Resolving deltas: 100% (68/68), done.
Submodule 'ufsctex' (https://github.com/royertiago/ufsctex) registered for path 'ufsctex'
Cloning into 'D:/User/Downloads/New folder/ufsctex-template/ufsctex'...
Submodule path 'ufsctex': checked out 'c805f360451854cfdd4b26252e4eb05d8d84fa34'

$ cd ufsctex-template/
$ latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode" -use-make template.tex
Latexmk: This is Latexmk, John Collins, 19 Jan. 2017, version: 4.52c.
Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex -interaction=nonstopmode  -recorder  "template.tex"'
------------
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6300)
entering extended mode
(template.tex
LaTeX2e <2017-04-15>
Babel <3.9r> and hyphenation patterns for 76 language(s) loaded.
(ufsctex/ufsctex.cls
(D:\User\Documents\latex\texmfs\install\tex\latex\base\inputenc.sty
(D:\User\Documents\latex\texmfs\install\tex\latex\base\utf8.def
(D:\User\Documents\latex\texmfs\install\tex\latex\base\t1enc.dfu)
(D:\User\Documents\latex\texmfs\install\tex\latex\base\ot1enc.dfu)
(D:\User\Documents\latex\texmfs\install\tex\latex\base\omsenc.dfu)))
(D:\User\Documents\latex\texmfs\install\tex\latex\base\fontenc.sty
(D:\User\Documents\latex\texmfs\install\tex\latex\base\t1enc.def))

LaTeX Warning: You have requested document class `ufsctex/ufsctex',
               but the document class provides `ufsctex'.

Document Class: ufsctex

! LaTeX Error: File `abnt.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name:
! Emergency stop.
<read *>

l.33

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on template.log.
=== TeX engine is 'pdfTeX'
===========Latexmk: Missing input file: 'abnt.cls' from line
  '! LaTeX Error: File `abnt.cls' not found.'
Latexmk: Missing input file: 'abnt.cls' from line
  '! LaTeX Error: File `abnt.cls' not found.'
Latexmk: 'pdflatex': source file 'abnt.cls' doesn't exist. I'll try making it...
------------
Running 'make "abnt.cls"'
------------
make: *** No rule to make target 'abnt.cls'.  Stop.
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'template.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
```

**Comment by evandrocoan** [comment]
Fiz um novo template https://github.com/evandrocoan/ufscthesisx com o abntex2 continuando a partir do fork de https://github.com/AdrianoRuseler/abntex2-ufsc, que é um fork de https://github.com/mateusduboli/ufsc-thesis-latex
